/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 gun.gltf 
Author: lokeig (https://sketchfab.com/lokeig)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/ak-47-384565b1779c450b90397232163e4e6d
Title: AK-47
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/gun.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.001}>
        <group position={[4963.263, 201.501, 378.356]} rotation={[0, Math.PI / 2, 0]}>
          <mesh geometry={nodes['r_woodLower_low_Material_#44_0'].geometry} material={materials.Material_44} position={[378.356, 8.459, 107.493]} />
        </group>
        <mesh geometry={nodes['bm_magazine_low_Material_#44_0'].geometry} material={materials.Material_44} position={[4705.263, -2.506, 380.224]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['u_dustcoverHolder_low_Material_#44_0'].geometry} material={materials.Material_44} position={[4589.468, 261.195, 379.581]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['r_flap_low_Material_#44_0'].geometry} material={materials.Material_44} position={[4751.41, 237.612, 437.223]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['r_upperCylinderHole_low_Material_#44_0'].geometry} material={materials.Material_44} position={[5222.409, 277.407, 380.527]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['l_stockWood_low_Material_#44_0'].geometry} material={materials.Material_44} position={[3987.749, 144.636, 379.581]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['m_safetyswitch_low_Material_#44_0'].geometry} material={materials.Material_44} position={[4385.055, 201.456, 425.143]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['bm_triggerBasePart_low_Material_#44_0'].geometry} material={materials.Material_44} position={[4538.905, 107.379, 378.892]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['bl_grip_low_Material_#44_0'].geometry} material={materials.Material_44} position={[4313.995, 52.883, 379.58]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['r_buttons_high_Material_#44_0'].geometry} material={materials.Material_44} position={[4778.076, 241.436, 354.477]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['ls2_button3_low_Material_#44_0'].geometry} material={materials.Material_44} position={[4675.745, 180.089, 340.422]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['ls2_button2_low_Material_#44_0'].geometry} material={materials.Material_44} position={[4741.717, 216.942, 340.422]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['r_button3_low_Material_#44_0'].geometry} material={materials.Material_44} position={[4776.58, 216.942, 419.132]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['l_button2_low_Material_#44_0'].geometry} material={materials.Material_44} position={[4340.587, 188.737, 419.132]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['l_button1_low_Material_#44_0'].geometry} material={materials.Material_44} position={[4273.388, 216.81, 419.132]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['r_button2_low_Material_#44_0'].geometry} material={materials.Material_44} position={[4740.771, 216.199, 419.043]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['ls2_button1_low_Material_#44_0'].geometry} material={materials.Material_44} position={[4777.213, 215.996, 340.511]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['r_button1_low_Material_#44_0'].geometry} material={materials.Material_44} position={[4675.054, 180.385, 419.043]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['rs2_button2_low_Material_#44_0'].geometry} material={materials.Material_44} position={[4340.647, 188.634, 340.489]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['rs2_button1_low_Material_#44_0'].geometry} material={materials.Material_44} position={[4272.14, 215.337, 340.489]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['m_button2_low_Material_#44_0'].geometry} material={materials.Material_44} position={[4515.429, 174.518, 340.004]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['m_button3_low_Material_#44_0'].geometry} material={materials.Material_44} position={[4548.31, 168.658, 340.004]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['m_button1_low_Material_#44_0'].geometry} material={materials.Material_44} position={[4433.928, 159.137, 340.004]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['r_numberSwitch_low_Material_#44_0'].geometry} material={materials.Material_44} position={[4881.506, 307.321, 406.382]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['r_numberSwitchButton_low_Material_#44_0'].geometry} material={materials.Material_44} position={[4881.648, 306.972, 405.455]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['ur_numberHolder1_Material_#44_0'].geometry} material={materials.Material_44} position={[4779.565, 319.707, 379.941]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['r_numberBaseCircle_low_Material_#44_0'].geometry} material={materials.Material_44} position={[4880.105, 306.616, 360.541]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['ur_woodUpper_low_Material_#44_0'].geometry} material={materials.Material_44} position={[5021.082, 282.682, 379.581]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['r_Connector_low_Material_#44_0'].geometry} material={materials.Material_44} position={[5310.431, 253.282, 379.581]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['r_woodholderLowerRight_low_Material_#44_0'].geometry} material={materials.Material_44} position={[5144.649, 214.63, 374.365]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['r_barrelAim_low_Material_#44_0'].geometry} material={materials.Material_44} position={[5544.018, 260.728, 379.584]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['r_barrelAimCylinder_low_Material_#44_0'].geometry} material={materials.Material_44} position={[5551.185, 293.478, 379.584]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['r_barrelEnd_low_Material_#44_0'].geometry} material={materials.Material_44} position={[5602.192, 228.645, 379.581]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['r_barrelHolder_low_Material_#44_0'].geometry} material={materials.Material_44} position={[5168.474, 225.292, 379.668]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['bm_triggerBase_low_Material_#44_0'].geometry} material={materials.Material_44} position={[4480.063, 117.671, 379.353]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['r_lowerCylinder_low_Material_#44_0'].geometry} material={materials.Material_44} position={[5339.954, 194.919, 378.945]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['r_barrel_low_Material_#44_0'].geometry} material={materials.Material_44} position={[5358.562, 225.292, 379.581]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['l_stockMetal_low_Material_#44_0'].geometry} material={materials.Material_44} position={[3730.269, 144.636, 379.581]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['l_stockBase_low_Material_#44_0'].geometry} material={materials.Material_44} position={[4211.979, 223.924, 379.581]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['bm_magazineBottom_low_Material_#44_0'].geometry} material={materials.Material_44} position={[4817.488, -157.941, 378.919]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['r_woodholderLeft_low_Material_#44_0'].geometry} material={materials.Material_44} position={[4900.851, 282.936, 379.581]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['r_woodholderUpperRight_low_Material_#44_0'].geometry} material={materials.Material_44} position={[5137.699, 283.319, 379.581]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['r_woodholder_low_Material_#44_0'].geometry} material={materials.Material_44} position={[5151.051, 242.352, 377.784]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['r_connectorPart2_low_Material_#44_0'].geometry} material={materials.Material_44} position={[5350.727, 200.235, 379.833]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['r_connectorPart1_low_Material_#44_0'].geometry} material={materials.Material_44} position={[5315.679, 209.562, 379.581]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['m_base_low_Material_#44_0'].geometry} material={materials.Material_44} position={[4534.814, 185.135, 379.801]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['bm_trigger_low_Material_#44_0'].geometry} material={materials.Material_44} position={[4434.721, 127.218, 379.523]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['bm_magazinePart3_low_Material_#44_0'].geometry} material={materials.Material_44} position={[4551.718, 167.051, 377.199]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['bm_magazinePart1_low_Material_#44_0'].geometry} material={materials.Material_44} position={[4610.025, 174.65, 399.93]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['u_dustcover_low_Material_#44_0'].geometry} material={materials.Material_44} position={[4503.333, 268.105, 379.581]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['ul_dustcoverScroll_low_Material_#44_0'].geometry} material={materials.Material_44} position={[4273.861, 274.384, 378.807]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['r_baseNumber1_low_Material_#44_0'].geometry} material={materials.Material_44} position={[4778.035, 245.75, 407.201]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['r_numberBase_low_Material_#44_0'].geometry} material={materials.Material_44} position={[4823.325, 284.837, 379.941]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['ur_numberBase2_low_Material_#44_0'].geometry} material={materials.Material_44} position={[4818.431, 314.256, 379.941]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['ur_number_low_Material_#44_0'].geometry} material={materials.Material_44} position={[4802.501, 327.478, 380.075]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['l_beltHolder_low_Material_#44_0'].geometry} material={materials.Material_44} position={[3848.358, 68.451, 379.338]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['l_belt_low_Material_#44_0'].geometry} material={materials.Material_44} position={[3849.364, 46.38, 379.359]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['l_stockScrew_low_Material_#44_0'].geometry} material={materials.Material_44} position={[4203.132, 227.611, 379.433]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['bm_triggerBaseButton4_low_Material_#44_0'].geometry} material={materials.Material_44} position={[4544.703, 142.575, 400.044]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['bm_triggerBaseButton3_low_Material_#44_0'].geometry} material={materials.Material_44} position={[4528.9, 142.575, 400.044]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['bm_triggerBaseButton2_low_Material_#44_0'].geometry} material={materials.Material_44} position={[4544.703, 142.575, 358.73]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['bm_triggerBaseButton1_low_Material_#44_0'].geometry} material={materials.Material_44} position={[4528.9, 142.575, 358.73]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['r_baseNumber2_low_Material_#44_0'].geometry} material={materials.Material_44} position={[4778.035, 245.75, 352.699]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['ur_numberHolder2_Material_#44_0'].geometry} material={materials.Material_44} position={[4779.565, 319.707, 379.941]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['bm_magazinePart2_low_Material_#44_0'].geometry} material={materials.Material_44} position={[4610.025, 174.65, 360.021]} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/gun.gltf')
